### ISSUE TITLE
Turn Off Vendor Prefixing

### ISSUE THREAD

**Issue by Ne-Ne** [emmetio/emmet-docs#26]
Hey All,

I am using Compass alongside SCSS (SASS) however I which to remove the vendor short-codes for emmet, as they are slowing down my workflow.

e.g. border radius

Is it possible to do this? I could avoiding needing to delete them, just disable this functionality.

-Neil

**Comment by dalgard** [comment]
Same here. Those are the contents of my `Emmet.sublime-settings` file and it happily inserts prefixes whenever I press tab around some properties. Stuff like this should not be enabled by default unless it presents *the* best solution out there – which it doesn't.

**Comment by andrewdc** [comment]
+1 - I have tried everything here (at least as best as I can tell) and I just cannot stop the prefixing. Any help would be great. 

Sublime Text 3. 
My Emmet.sublim-settings:

{
    "preferences": {
        "sass.propertyEnd": ";",
        "css.autoInsertVendorPrefixes": false,
        "scss.autoInsertVendorPrefixes": false,
        "autoInsertCssPrefixedEnabled": false
    }
}

Am I missing something obvious here?
Thanks all!

**Comment by nicasi** [comment]
Using Sublime Text 3 the easiest thing to do is to make a folder called *emmet* in your users folder. In Windows that's C:\users\\*your_user_name*

In this folder you can place preferences.json and if you want to customize snippets also snippets.json

In preferences.json you put something like this:

    {
        "css.autoInsertVendorPrefixes":false
    }

More info here:
https://github.com/sergeche/emmet-sublime#extensions-support

Here are the preferences and their defaults:
http://docs.emmet.io/customization/preferences/

**Comment by geebru** [comment]
@nicasi - The issue (at least for me) is no longer getting the preference to work but how it's working with Flexbox.

With that option set to false, typical vendor-prefixed items are not prefixed, which is great and how it should work.

The problem with using `df` which should result in `display: flex;` is that the vendor prefixes for flex don't exist in the property but the value.

With the option set to false, the values of `display: flex;` continue to be prefixed.

It's not a deal breaker as typing `display: flex;` doesn't take much time but the option / preference doesn't seem to extend to values, only properties.

**Comment by nicooprat** [comment]
Seems like a bug to me! Here's my `~/emmet/preferences.json` file:

````json
{
  "css.autoInsertVendorPrefixes": false,
  "less.autoInsertVendorPrefixes": false,
  "scss.autoInsertVendorPrefixes": false,
  "sass.autoInsertVendorPrefixes": false,
  "caniuse.enabled": false,
  "caniuse.vendors": false,
}
`````

(Using Atom 1.11.0-beta5)

**Comment by sergeche** [comment]
`display: flex` is actually a snippet, it’s not generated by CSS module. So you have to redefine `df` snippet as described here: http://docs.emmet.io/customization/snippets/

**Comment by nicooprat** [comment]
Thanks for your quick answer. Indeed, it works with this `~/emmet/snippets.json`:

````json
{
  "css": {
    "snippets": {
      "d:f": "display:flex;"
    }
  }
}
````

But I don't understand this behavior, since in the original file nothing differs between `"d:f"` and the others snippets... https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L100 Why is this one different?

**Comment by sergeche** [comment]
Current CSS implementation simply checks if given property is available with standard vendor prefixes. In case of `display: flex` it actually requires more complex logic which that have to check which value should be inserted into specific vendor property. It’s not currently supported but might be available in future versions

**Comment by nicooprat** [comment]
Ok, thanks for the explanation! I think more and more developers use tools like Autoprefixer nowadays, so it could be cool to have this behavior disabled by default or an option to disable vendor prefixes completely.

**Comment by sergeche** [comment]
I agree, I might even add Autoprefixer itself as optional Emmet plugin so it can generate much better output for vendor prefixes
