### ISSUE TITLE
`>input` wrongly yields an inline result.

### ISSUE THREAD

**Issue by JohnLukeBentley** [emmetio/emmet-docs#62]
When using the nesting operator `>` with `input` the result is an inline nesting within the parent element rather than having `input` on separate lines within the nesting. 

```html
<!-- Expected -->
form>p*4
<form action="">
  <p></p>
  <p></p>
  <p></p>
  <p></p>
</form>

<!-- Unexpected -->
form>input*4
<form action=""><input type="text"><input type="text"><input type="text"><input type="text"></form>

<!-- Unexpected, it's not a problem with the form element -->
p>input*4
<p><input type=""><input type="text"><input type="text"><input type="text"></p>
```

(Using Emmet in Visual Studio Code)

I'm relatively new to Emmet so I can't rule out if this is intended behaviour.

**Comment by sergeche** [comment]
`input` is inline element so Emmet tries to lay them down in a single line if amount is too small.
You can control this behaviour with [`output.inlineBreak`](https://github.com/emmetio/emmet/blob/master/src/config.ts#L129) option

**Comment by JohnLukeBentley** [comment]
Thanks @sergeche. I note `"output.inlineBreak": 1` sets all elements to block level. So we get, for example ...

```
  <form action="">
    <input type="text" />
    <input type="text" />
    <input type="text" />
    <input type="text" />
  </form>
```
